version: "3.8"
services:
  movies:
    depends_on:
        - mongodb
    command: node src/app.js
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - published: ${APP_PORT:-4000}
        target: 4000
    volumes:
      - .:/app/
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
    stdin_open: true
    tty: true
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

# named volumes to preserve data between restarts  
volumes:
  db: